import Link from 'next/link'
import '../src/global.css'
import { FaWhatsapp } from "react-icons/fa";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <nav className='flex justify-between my-4 mx-2 px-4 text-lg'>
          <Link href="/">LOGO</Link>
          <ul className='flex '>
            <li className='px-4'><a href="/">Inicio</a></li>
            <li className='px-4'><a href="">Nosotras</a></li>
            <li className='px-4'><a href="">Productos</a></li>
            <li className='px-4'><a href="">Talleres</a></li>
            <li className='px-4'><a href="/contact">Contacto</a></li>
          </ul>
          <a href="#"><FaWhatsapp /></a>
        </nav>
        {children}
      </body>
    </html>
  )
}
