import { Quicksand } from "next/font/google";
import "./styleF.css";

// Components
import Footer from "../components/footer/Footer";

export const metadata = {
  title: "Pa'l Alma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body >
        <Footer />
        {children}
      </body>
    </html>
  );
}