import { Quicksand } from "next/font/google";
import "./global.css";

// Components
import Navbar from "../components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Pa'l Alma",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={quicksand.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
